config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs

  devise_for :users
  root 'pages#home'

end

app/models/job.rb
class Job < ActiveRecord::Base
  
  def self.search(search)
    if search
      find(:all, :contidions => ['title LIKE ?', 'description LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
  
  include PgSearch
  pg_search_scope :search, against: [:description, :title, :list_snippet]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:search]
    @jobs = Job.search(params[:search])
    else
    @jobs = Job.all
    end
  end

  def show
    respond_with(@job)
  end

  def new
    @job = Job.new
    respond_with(@job)
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:description, :title, :close_date, :list_snippet, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.haml
= form_for(@job) do |f|
  - if @job.errors.any?
    #error_explanation
      %h2
        = pluralize(@job.errors.count, "error")
        prohibited this job from being saved:
      %ul
        - @job.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :title
    %br/
    = f.text_field :title, class: "form-control", placeholder: "e.g. Casual Retail Assistant"
    
  .form-group
    = f.label :description
    %br/
    = f.text_area :description, class: "form-control wysihtml5", rows: "20", style: "resize:none"
    
  .form-group
    = f.label :close_date
    %br/
    = f.text_field :close_date, class: "form-control", placeholder: "dd/mm/yyyy"
    
  .form-group
    = f.label :location
    %br/
    = f.select :location, options_for_select([['Sydney', 'Sydney'], ['Melbourne', 'Melbourne'], ['Brisbane', 'Brisbane']])
    
  .form-group
    = f.label :list_snippet
    %br/
    = f.text_area :list_snippet, class: "form-control", placeholder: "This is what will be shown in the list view (max 250 char)", rows: "8"
    
  .form-group
    = f.submit class: "btn btn-primary"

app/views/jobs/edit.html.haml
.container
  .row
    .col-md-9
      .panel.panel-default
        .panel-heading
          %h1 Edit job
        .panel-body
          = render 'form'

app/views/jobs/index.html.haml
.container
  .row
    .col-md-3
    
    .col-md-9
      .panel.panel-default
        .panel-heading
          Job Search
        .panel-body
          = form_tag jobs_path, method: "get" do
            .row
              .col-md-10.form-group
                = text_field_tag :search, params[:search], class: "form-control"
              .col-md-1.form-group
                = submit_tag "Search", :name => nil, class: "btn btn-default"

        
      - @jobs.each do |job|
        .panel.panel-default
          .panel-heading
            %strong
              = job.title
          .panel-body
            = simple_format job.list_snippet
            = job.location
            = link_to "View", job

app/views/jobs/new.html.haml
.container
  .row
    .col-md-9
      .panel.panel-default
        .panel-heading
          %h1 New job
        .panel-body
          = render 'form'
        

app/views/jobs/show.html.haml
.container
  %p#notice= notice
  .row
    .col-md-9
      .panel.panel-default
        .panel-heading
          %h1
            = @job.title
      
        .panel-body
  
          = simple_format @job.description
      
          %p
          %strong
            Closing Date
            = @job.close_date
        
        .panel-footer
          .btn.btn-primary.btn-lg
            Apply Now
    .col-md-3

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand
        Operation-X
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Jobs", jobs_path
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Log In", new_user_session_path
        %li
          = link_to "Sign Up", new_user_registration_path
          
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title OperationX
    = stylesheet_link_tag 'application', media: 'all'
    %link{:href => "http://fonts.googleapis.com/css?family=Hind:400,300,500", :rel => "stylesheet", :type => "text/css"}
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/nav"
    
    - flash.each do |name, msg|
      = content_tag(:div, msg, class: "alert alert-#{name}")
      
    = yield

app/views/pages/home.html.haml
#splash
  .container
    .center
      %h1
        The number one job search site for
        %br
        High School and University students
    #searchbox.clearfix
      %form{:role => "form"}
        .form-group
          %input.form-control{type: 'text', placeholder: 'Enter keywords'}
        .row
          .col-md-3
            .dropdown 
              %button#menu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                Location
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "menu1", :role => "menu"}
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} HTML
                
          .col-md-3
            .dropdown
              %button#menu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                Work Type
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "menu1", :role => "menu"}
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} HTML
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} CSS
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} JavaScript
                %li.divider{:role => "presentation"}
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} About Us
          .col-md-3
            .dropdown
              %button#menu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                Category
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "menu1", :role => "menu"}
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} HTML
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} CSS
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} JavaScript
                %li.divider{:role => "presentation"}
                %li{:role => "presentation"}
                  %a{:href => "#", :role => "menuitem", :tabindex => "-1"} About Us
                  
          .col-md-3
            %button.btn.btn-success{:type => "submit"} 
              %span.glyphicon.glyphicon-search
              Search
      